# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_payload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='data'),
        ),
    ]
